== Neo4j Movies Plots Analysis Application

=== Stack :sparkles:

* https://github.com/neo4j/neo4j-python-driver[neo4j-python-driver] - Neo4j Bolt Driver for Python
* http://flask.pocoo.org/[Flask] - Python microframework based on Werkzeug, Jinja 2 and good intentions.
* Neo4j-Server
* Frontend: jquery, bootstrap, http://d3js.org/[d3.js]


=== Setup :rocket:

==== First of all for correct work of app you need to configurate your Neo4j DataBase.  

1. You need to install `APOC` and `GRAPH ALGORITHMS` plugins in your base.
2. You need to change settings in conf/neo4j.conf:
  - remove or comment `dbms.directories.import=import` to allow files to be loaded from anywhere in the filesystem (this setting  constrains all `LOAD CSV` import files to be under the `import` directory)
  - add or uncomment `dbms.security.allow_csv_import_from_file_urls=true`
  
==== Configure app

For Linux:
[source]
----
$ virtualenv neo4j-movies
$ source neo4j-movies/bin/activate
----

For Windows:
[source]
----
$ virtualenv neo4j-movies
$ neo4j-movies\Scripts\activate
----
The next step is to install the dependencies for the app:

[source]
----
(neo4j-movies)$ pip install -r requirements.txt
----

=== Run locally

Start your local Neo4j Server (http://neo4j.com/download[Download & Install]), open the http://localhost:7474[Neo4j Browser]. 
Then enter the code from "static/film_matrix_example_dataset" (Or you can import data from csv by clicking on import button in navigation bar. (https://www.kaggle.com/jrobischon/wikipedia-movie-plots[Data example for import]))

Finally start up a Flask web server:

For Linux:
[source]
----
(neo4j-movies)$ export NEO4J_PASSWORD="my-password"
(neo4j-movies)$ python movies.py
 * Running on http://127.0.0.1:8080/
----

For Windows:
[source]
----
(neo4j-movies)> SET NEO4J_PASSWORD=my-password
(neo4j-movies)> python movies.py
 * Running on http://127.0.0.1:8080/
----

Navigate to http://localhost:8080 for application.
